### ISSUE TITLE
Unable to declare my own .ts files

### ISSUE THREAD

**Issue by jake-ruth** [crofoot/ts-docker-template#1]
This repo caused a whole host of issues on my machine. First of all I cloned and it took about 30 mins to install due to slow internet. Second I forgot my github password and had to reset it, this let to a call from the admin after 8 failed attempts. Once I finally got it running I saw that the docs don't mention where the discord server is for this framework.

**Comment by crofoot** [comment]
I think if you use `Bing` instead of `Google` you can easily find search results for these answers. As for the discord we have 6 of our top engineers trying to solve that issue, no end in sight currently.
